FROM rosnoetic-focal:base

RUN apt-get update

RUN rosdep init
RUN rosdep update

RUN mkdir ros_catkin_ws
WORKDIR ros_catkin_ws

RUN rosinstall_generator ros_comm --rosdistro noetic --deps --wet-only --tar > minimal.rosinstall
RUN wstool init -j8 src minimal.rosinstall
RUN rosdep install --from-paths src --ignore-src --rosdistro noetic -y -r
RUN src/catkin/bin/catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release --install-space /opt/ros/noetic

CMD /bin/bash
